Repository moodCatcherProject/Back-End, pull requests merged in 2022-09, with the labels that each got.

#20 PR: feature/kakaoLogin checkType 1.1버젼 추가
  src/layers/_router.loader.js
  src/layers/exceptModels/exception/custom.exception.js
  src/layers/exceptModels/form/checkType.js
  test/gwonsTest.js
Labels: enhancement

#21 PR : feature/post
  public/index.html
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/passport/index.js
  src/layers/passport/kakaoStrategy.js
  src/layers/routes/auth.router.js
  src/layers/routes/middlewares/error.js
  src/sequelize/models/post.js
  src/sequelize/models/startmessage.js
  src/sequelize/models/user.js
  test/login.test.js
Labels: enhancement

#23 PR : `feature logout API` 로그아웃 기능 추가, auth 미들웨어 추가
  src/layers/_router.loader.js
  src/layers/routes/auth.router.js
  src/layers/routes/user.router.js
Labels: enhancement

#24 PR : Feature/sign up 병합
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
  src/sequelize/config/config.js
Labels: enhancement

#25 PR : 게시물 작성기능 테스트 완료, 게시물 수정기능 구현 중
  src/app.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/post.router.js
  src/layers/services/post.service.js
Labels: enhancement

#26 PR : `Feature/sign up`
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
Labels: enhancement

#28 PR :feature/post
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
Labels: bug

#30 PR : husky, prettier, lint-staged 환경설정
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/pull_request_template.md
  .husky/pre-commit
  .prettierrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  src/layers/routes/user.router.js
Labels: enhancement

#31 PR : husky 변경사항 추가설정
  .prettierrc.js
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/item.controller.js
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/_.models.loader.js
  src/layers/exceptModels/exception/custom.exception.js
  src/layers/passport/index.js
  src/layers/passport/kakaoStrategy.js
  src/layers/passport/localStrategy.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/Item.router.js
  src/layers/routes/auth.router.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/middlewares/config/s3.js
  src/layers/routes/middlewares/error.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/post.router.js
  src/layers/services/auth.service.js
  src/layers/services/post.service.js
  src/layers/services/searchService.js
  src/nodeScheduller.js
  src/sequelize/config/config.js
  src/server.js
  test/gwonsTest.js
  test/login.test.js
Labels: enhancement

#32 PR : [👏] 변경사항 `프리티어 적용`
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/post.router.js
  src/layers/services/post.service.js
  src/sequelize/config/config.js
  test/login.test.js
Labels: enhancement

#33 PR : husky 모듈 삭제 `package.json/package.lock.json`
  .husky/pre-commit
  package-lock.json
  package.json
Labels: bug

#34 PR `Feature/sign up`
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
Labels: bug

#35 PR : `feature signUp API`
  src/layers/controllers/auth.controller.js
  src/layers/controllers/user.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routes/auth.router.js
  src/layers/routes/user.router.js
  src/layers/services/auth.service.js
  src/layers/services/user.service.js
  src/sequelize/config/config.js
  test/login.test.js
Labels: enhancement

#36 PR : 에러처리, 미들웨어 메세지 수정 `feature localLogin API`
  src/layers/passport/localStrategy.js
  src/layers/routes/middlewares/authMiddle.js
Labels: enhancement

#38 deleteUser 삭제
  src/layers/repositories/auth.repository.js
Labels: bug

#45 `feature comment API`
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/routes/comment.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  test/login.test.js
  test/lsb.test.js
Labels: enhancement

#46 PR : 유저 정보 조회, 수정 기능 구현 `feature user API`
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/user.controller.js
  src/layers/repositories/user.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/user.router.js
  src/layers/services/user.service.js
Labels: enhancement

#47 PR : 미들웨어 적용 `feature 유저 정보 조회 API`
  src/layers/routes/user.router.js
Labels: enhancement

#51 ✅ db 테스트 데이터 넣는 파일 추가, 전체게시물 조회 기능, autoCicd
  .github/workflows/Node.js.yml
  .github/workflows/node.js.yml
  package.json
  src/app.js
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/controllers/startMsg.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/post.router.js
  src/layers/services/allPosts.service.js
  src/layers/services/post.service.js
  src/sequelize/migrations/20220830044257-create-user-detail.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
  src/sequelize/models/comment.js
  src/sequelize/models/like.js
  src/sequelize/models/notices.js
  src/sequelize/models/post.js
  src/sequelize/models/user.js
  src/sequelize/models/userdetail.js
  startMsg.js
  startMsg.txt
  test/dbMockData.js
  test/gwonsTest.js
Labels: enhancement

#54 PR : 기능 구현 완료 및 파일트리 정리 `feature 크롤링 API`
  src/layers/_router.loader.js
  src/layers/controllers/item.controller.js
  src/layers/routes/Item.router.js
  src/layers/services/item.Service.js
Labels: enhancement

#55 PR : `develop branch` 에서 `main branch`로 병합
  src/layers/_router.loader.js
  src/layers/controllers/item.controller.js
  src/layers/routes/Item.router.js
  src/layers/services/item.Service.js
Labels: enhancement

#56 PR : model 및 migration 수정
  src/sequelize/migrations/20220830043428-create-user.js
  src/sequelize/migrations/20220830044257-create-user-detail.js
  src/sequelize/migrations/20220830044838-create-like.js
  src/sequelize/migrations/20220830045109-create-post.js
  src/sequelize/models/comment.js
  src/sequelize/models/item.js
  src/sequelize/models/like.js
  src/sequelize/models/notices.js
  src/sequelize/models/post.js
  src/sequelize/models/recomment.js
  src/sequelize/models/user.js
  src/sequelize/models/userdetail.js
Labels: enhancement

#57 PR : `Feature/comment`
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/recomment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/routes/comment.router.js
  src/layers/routes/recomment.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/recomment.service.js
  src/layers/services/user.service.js
  test/login.test.js
  test/lsb.test.js
Labels: enhancement

#58 PR : post model 및 migration 수정
  src/sequelize/migrations/20220830045109-create-post.js
  src/sequelize/models/post.js
Labels: enhancement

#59 PR : 변경사항 commit 참고
  src/layers/controllers/user.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/user.router.js
  src/layers/services/auth.service.js
  src/layers/services/user.service.js
  src/sequelize/migrations/20220830044838-create-like.js
Labels: enhancement

#60 ✅스타트 메시지 기능 구현, auth미들웨어 구현, res.locals에 User, UserDetail 넣었음. 전체 게시물 조회 필터기능 1차 구현'
  package-lock.json
  package.json
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/controllers/start.controller.js
  src/layers/controllers/startMsg.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/post.router.js
  src/layers/routes/start.router.js
  src/layers/services/allPosts.service.js
  src/layers/services/post.service.js
  test/dbMockData.js
Labels: enhancement

#61 PR : `Feature/comment`
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/recomment.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/routes/comment.router.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/recomment.service.js
Labels: enhancement

#62 PR : jwt로그인 방식으로 변경 후 userId를 local storage에서 가져오기
  src/layers/controllers/auth.controller.js
  src/layers/controllers/user.controller.js
Labels: enhancement

#63 ✅게시물 전체조회 수정
  src/app.js
  src/layers/repositories/post.repository.js
  src/layers/services/allPosts.service.js
Labels: enhancement

#65 PR : 파일 이름 변경 `item.router.js`
  src/layers/routes/item.router.js
Labels: bug

#67 PR : 로그인 세션 주석처리 `app.js`
  src/app.js
Labels: bug

#68 PR : 로그인 세션 주석처리 `app.js`
  src/app.js
Labels: bug

#69 👏 cors 문제 해결중
  src/app.js
Labels: bug

#70 👏cors 문제 해결중
  src/app.js
Labels: bug

#73 👏전체 게시물 조회, 닉네임 중복 확인, 로그인 미들웨어 에러처리
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/middlewares/error.js
  src/layers/services/allPosts.service.js
  test/dbMockData.js
  test/login.test.js
Labels: bug

#74 👏전체 게시물 조회, 닉네임 중복 확인, 로그인 미들웨어 에러처리
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/middlewares/error.js
  src/layers/services/allPosts.service.js
  test/dbMockData.js
  test/login.test.js
Labels: bug

#76 👏findByNickname 고치기
  src/layers/services/auth.service.js
  test/dbMockData.js
Labels: bug

#77 👏findByNickname 고치기
  src/layers/services/auth.service.js
  test/dbMockData.js
Labels: bug

#78 👏로그인 기능 token 빈값 추가
  src/layers/routes/middlewares/authMiddle.js
Labels: bug

#79 👏로그인 기능 token 빈값 추가
  src/layers/routes/middlewares/authMiddle.js
Labels: bug

#80 👏res.header. 삭제
  src/layers/controllers/auth.controller.js
Labels: bug

#81 👏tokenValue !== undefined,null 추가
  src/layers/routes/middlewares/authMiddle.js
Labels: bug

#82 👏tokenValue !== undefined,null 추가
  src/layers/controllers/auth.controller.js
  src/layers/routes/middlewares/authMiddle.js
Labels: bug

#84 PR : isNotLoggedIn 미들웨어 수정
  src/layers/_router.loader.js
  src/layers/controllers/like.controller.js
  src/layers/routes/item.router.js
  src/layers/routes/like.router.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/services/like.service.js
Labels: bug

#90 👏전 체게시물 조회 필터기능 오류 해결, isNotLoggdin 에러 처리 , 테스트 코 드 모두 작동되도록 수정, 내가 좋아요 한 게시물 보기 에러처리
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/auth.router.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/post.router.js
  src/layers/services/allPosts.service.js
  src/layers/services/post.service.js
  test/login.test.js
  test/post.test.js
Labels: bug

#94 ✅feature/point무드포인트 적립기능 추가
  src/layers/controllers/auth.controller.js
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/_.models.loader.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/passport/kakaoStrategy.js
  src/layers/repositories/auth.repository.js
  src/layers/routes/start.router.js
  src/sequelize/migrations/20220830044257-create-user-detail.js
  src/sequelize/migrations/20220907051805-create-mood-point.js
  src/sequelize/models/moodpoint.js
  src/sequelize/models/userdetail.js
  test/dbMockData.js
Labels: enhancement

#95 PR : 기능 구현 완료 `feature like API`
  src/layers/controllers/like.controller.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/like.router.js
  src/layers/services/like.service.js
Labels: enhancement

#97 PR : `develop branch`에서 `main branch`로 병합
  src/layers/controllers/auth.controller.js
  src/layers/controllers/like.controller.js
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/_.models.loader.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/passport/kakaoStrategy.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/like.router.js
  src/layers/routes/start.router.js
  src/layers/services/item.Service.js
  src/layers/services/like.service.js
  src/sequelize/migrations/20220830044257-create-user-detail.js
  src/sequelize/migrations/20220907051805-create-mood-point.js
  src/sequelize/models/moodpoint.js
  src/sequelize/models/userdetail.js
  test/dbMockData.js
Labels: enhancement

#98 PR : `Feature/comment`
  map.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/services/comment.service.js
  test/lsb.test.js
Labels: enhancement

#99 PR : `Featrue/comment`
  map.js
  src/layers/controllers/comment.controller.js
  src/layers/repositories/comment.repository.js
  src/layers/services/comment.service.js
  test/lsb.test.js
Labels: enhancement

#101 ✅전체게시물 기능 구현, res 데이터 가공, 지금부터 24시간 전부터 지금까지 게시물 출력 기능 구현
  mysql.md
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/repositories/post.repository.js
  src/layers/services/allPosts.service.js
  src/layers/services/post.service.js
  startMsg.js
Labels: enhancement

#103 PR : `Feature/comment`
  map.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/recomment.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/recomment.service.js
  test/lsb.test.js
Labels: enhancement

#104 ✅버전 1.1
  map.js
  mysql.md
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/comment.controller.js
  src/layers/controllers/like.controller.js
  src/layers/controllers/post.controller.js
  src/layers/controllers/recomment.controller.js
  src/layers/controllers/user.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/post.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/routes/like.router.js
  src/layers/routes/post.router.js
  src/layers/services/allPosts.service.js
  src/layers/services/auth.service.js
  src/layers/services/comment.service.js
  src/layers/services/post.service.js
  src/layers/services/recomment.service.js
  startMsg.js
  test/lsb.test.js
Labels: enhancement

#106 PR : likeStatus boolean 형으로 출력 변경 `게시글 상세조회 API` #105
  src/layers/controllers/post.controller.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/post.router.js
  src/layers/services/post.service.js
Labels: bug

#107 PR : likeStatus boolean 형으로 출력 변경 `게시글 상세조회 API` #105
  src/layers/controllers/post.controller.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/post.router.js
  src/layers/services/post.service.js
Labels: bug

#110 ✅👏유저정보 카카오와 로컬을 구분해서 사진 파일 줄 수 있도록 수정, 노드 스케줄러 구상, 알림 기능 구현
  package-lock.json
  package.json
  src/layers/_router.loader.js
  src/layers/controllers/notice.controller.js
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/_.models.loader.js
  src/layers/exceptModels/form/checkType.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/passport/kakaoStrategy.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/post.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/notice.router.js
  src/layers/routes/start.router.js
  src/layers/services/notice.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
  src/sequelize/models/notices.js
  src/sequelize/models/userdetail.js
  startMsg.js
  test/dbMockData.js
  test/notice.test.js
Labels: bug, enhancement

#111 ✅👏유저정보 카카오와 로컬을 구분해서 사진 파일 줄 수 있도록 수정, 노드 스케줄러 구상, 알림 기능 구현
  package-lock.json
  package.json
  src/layers/_router.loader.js
  src/layers/controllers/notice.controller.js
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/_.models.loader.js
  src/layers/exceptModels/form/checkType.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/passport/kakaoStrategy.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/post.repository.js
  src/layers/repositories/user.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/notice.router.js
  src/layers/routes/start.router.js
  src/layers/services/notice.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
  src/sequelize/models/notices.js
  src/sequelize/models/userdetail.js
  startMsg.js
  test/dbMockData.js
  test/notice.test.js
Labels: bug, enhancement

#112 👏이미지 업로드 가능
  src/layers/routes/middlewares/postImageUploadMiddleware.js
Labels: bug

#113 👏이미지 업로드 가능
  src/layers/routes/middlewares/postImageUploadMiddleware.js
Labels: bug

#117 👏게시물 테이블에 delete(boolean)추가 스케줄러 파일 생성
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/auth.service.js
  src/layers/services/like.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
  src/sequelize/migrations/20220830045109-create-post.js
  src/sequelize/models/post.js
  startMsg.js
  test/dbMockData.js
  test/post.test.js
Labels: bug

#118 PR : Conflicts Fix
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/auth.service.js
  src/layers/services/like.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
  src/sequelize/migrations/20220830045109-create-post.js
  src/sequelize/migrations/20220909081227-create-hot-post.js
  src/sequelize/models/hotpost.js
  src/sequelize/models/post.js
  startMsg.js
  test/dbMockData.js
  test/post.test.js
Labels: bug

#120 PR : 인기게시물 지정 및 조회, 무드포인트 적립 적용 'feature 인기 게시물 조회 API'
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/post.repository.js
  src/layers/services/post.service.js
  startMsg.js
Labels: enhancement

#121 PR : `Feature/comment`
  src/layers/services/comment.service.js
  src/layers/services/recomment.service.js
  test/lsb.test.js
Labels: enhancement

#122 PR : 변경사항 `알림 기능 완성, 스케줄러 구현 중`
  src/layers/controllers/auth.controller.js
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/post.repository.js
  src/layers/services/comment.service.js
  src/layers/services/post.service.js
  src/layers/services/recomment.service.js
  src/sequelize/migrations/20220830044452-create-notice.js
  src/sequelize/models/notices.js
  test/dbMockData.js
Labels: enhancement

#124 스케줄러 테스트 완료, 로그인 시 알림 출력되지 않는 문제 해결
  src/sequelize/config/config.js
Labels: bug, enhancement

#125 PR : notice 데이터 전송 방식 변경 data => notice
  src/layers/services/notice.service.js
Labels: bug

#126 PR : notice 데이터 전송 방식 변경 data => notice
  src/layers/services/notice.service.js
  src/sequelize/config/config.js
Labels: bug

#127 PR : moodPoint에 따른 유저 등급 update 구현 `feature scheduller`
  src/layers/exceptModels/form/scheduller.js
  startMsg.js
  test/user.test.js
Labels: enhancement

#129 feature/point
  src/app.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug, enhancement

#130 PR : 게시물 삭제기능 보완
  src/layers/controllers/post.controller.js
  src/layers/services/notice.service.js
  src/layers/services/post.service.js
  test/notice.test.js
Labels: bug

#131 PR : Bug Fix 게시물 사진 삭제, 유저 사진 삭제 S3 버킷 관련
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/post.router.js
  src/layers/routes/user.router.js
Labels: bug

#132 PR : `feature/comment`
  src/layers/services/comment.service.js
Labels: enhancement

#133 PR : MoodCatcher 1.1 ver
  src/app.js
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/routes/post.router.js
  src/layers/routes/user.router.js
  src/layers/services/comment.service.js
  src/layers/services/notice.service.js
  src/layers/services/post.service.js
  startMsg.js
  test/notice.test.js
  test/user.test.js
Labels: enhancement

#134 PR: 서버 배포 1.1
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/scheduller.js
  src/sequelize/models/index.js
  startMsg.js
  startMsg.txt
Labels: bug

#135 서버 배포 1.1
  src/layers/controllers/start.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/scheduller.js
  src/sequelize/models/index.js
  startMsg.js
  startMsg.txt
Labels: bug

#136 PR : 노드 스케줄러 게시물 사진 삭제기능 구현
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/sequelize/models/index.js
  test/notice.test.js
Labels: enhancement

#137 PR : 노드 스케줄러 게시물 사진 삭제기능 구현
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
  src/sequelize/models/index.js
  test/notice.test.js
Labels: enhancement

#140 PR : 서버에 올라갈 파일이 아니면 삭제, helmet, artllery 추가
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/routes/start.router.js
  src/nodeScheduller.js
  test/art.json
  test/dbMockData.js
Labels: bug, enhancement

#141 PR : 서버에 올라갈 파일이 아니면 삭제, helmet, artllery 추가
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/routes/start.router.js
  src/nodeScheduller.js
  test/art.json
  test/dbMockData.js
Labels: bug, enhancement

#142 PR : 하루 단위 사용자에게 하루동안 얻은 포인트 알림 출력
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
Labels: enhancement

#143 PR : 하루 단위 사용자에게 하루동안 얻은 포인트 알림 출력
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
Labels: enhancement

#144 PR : Like테이블에서 delete true 제거
  src/layers/repositories/post.repository.js
Labels: bug

#145 PR : Like테이블에서 delete true 제거
  src/layers/repositories/post.repository.js
Labels: bug

#146 createMessage hot fix
  src/layers/controllers/auth.controller.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#147 createMessage hot fix
  src/layers/controllers/auth.controller.js
  src/layers/exceptModels/form/notice.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#148 cors whitelist작성
  src/app.js
  src/layers/controllers/auth.controller.js
Labels: bug, enhancement

#149 PR : cors whitelist작성
  src/app.js
  src/layers/controllers/auth.controller.js
Labels: enhancement

#151 PR : 작성자 검색 수정
  src/app.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/post.repository.js
Labels: bug

#153 PR : `Bug Fix` updateGrade scheduller 기능 관련
  src/layers/controllers/auth.controller.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/services/post.service.js
  src/sequelize/migrations/20220909081227-create-hot-post.js
  src/sequelize/models/hotpost.js
  test/user.test.js
Labels: bug, enhancement

#154 cors hot fix
  src/app.js
Labels: bug

#155 cors hot fix
  src/app.js
Labels: bug

#156 PR : 스케줄러 시간변경
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#157 PR : 스케줄러 시간변경
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#158 PR : 스케줄러 시간변경
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#160 PR:대표게시물 핫픽스
  src/layers/repositories/post.repository.js
Labels: bug

#161 PR:대표게시물 핫픽스
  src/layers/repositories/post.repository.js
Labels: bug

#163 PR : 댓글 작성시에 방금 전 출력, imgUrl 수정 `feature/comment`
  Nodemailer.js
  package-lock.json
  package.json
  src/layers/controllers/comment.controller.js
  src/layers/services/comment.service.js
Labels: enhancement

#164 PR : createHotPost 동기처리
  src/layers/controllers/auth.controller.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#165 PR : createHotPost 동기처리
  src/layers/controllers/auth.controller.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#166 PR : Feature/point
  src/layers/controllers/auth.controller.js
  src/layers/repositories/post.repository.js
Labels: bug

#167 PR : redirect url 변경
  src/layers/controllers/auth.controller.js
  src/layers/repositories/post.repository.js
Labels: bug

#168 댓글 조회 출력방식 변경
  src/layers/services/comment.service.js
Labels: enhancement

#169 PR: 게시물 작성시 메시지 수정
  src/layers/exceptModels/form/moodPoint.js
Labels: enhancement

#170 PR : `댓글 조회 출력방식 변경`
  src/layers/exceptModels/form/moodPoint.js
  src/layers/services/comment.service.js
Labels: enhancement

#171 PR : 전체게시물 all
  src/layers/services/post.service.js
Labels: bug

#172 PR : 전체게시물 all
  src/layers/services/post.service.js
Labels: bug

#175 Update scheduller.js
  src/layers/exceptModels/form/scheduller.js
Labels: bug

#176 PR : 게시물 출력시 닉네임 같이 응답
  src/app.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/services/post.service.js
Labels: enhancement

#177 PR : 게시물 출력시 닉네임 같이 응답
  src/app.js
  src/layers/controllers/post.controller.js
  src/layers/repositories/post.repository.js
  src/layers/services/post.service.js
Labels: enhancement

#178 PR : cors 변경
  src/app.js
Labels: bug

#179 PR : cors 변경
  src/app.js
Labels: enhancement

#180 refactor : Resizing image at main(width:280px)
  .gitignore
  src/layers/controllers/post.controller.js
Labels: enhancement

#181 refactor : Resizing image at main(width:280px)
  .gitignore
  src/layers/controllers/post.controller.js
Labels: enhancement

#182 PR : `Feature/comment`
  .gitignore
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
Labels: enhancement

#184 PR : `feature/auth`
  .gitignore
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
Labels: enhancement

#185 PR : Fix: 비밀번호 변경API 다른사람의 비밀번호를 변경할수 있었던 점 에러처리
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
  test/lsb.test.js
Labels: bug

#186 feat: Create kakaoMap(ing...) refactor repositories of post and notice
  src/app.js
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/kakaoMap.controller.js
  src/layers/repositories/kakaoMap.repository.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/kakaoMap.router.js
  src/layers/services/kakaoMap.service.js
  src/public/index.css
  src/public/index.html
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
  src/server.js
Labels: enhancement

#187 PR : Reactor: Change cookie expiration time to 10 minutes
  src/layers/controllers/auth.controller.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
Labels: bug

#188 fix : throw error if empty post data
  .gitignore
  mysql.md
  src/app.js
  src/layers/services/post.service.js
  src/public/index.css
  src/public/index.html
Labels: bug

#189 fix : throw error if empty post data
  .gitignore
  mysql.md
  src/app.js
  src/layers/_router.loader.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/kakaoMap.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/kakaoMap.repository.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/post.repository.js
  src/layers/routes/auth.router.js
  src/layers/routes/kakaoMap.router.js
  src/layers/services/auth.service.js
  src/layers/services/kakaoMap.service.js
  src/layers/services/post.service.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
  src/server.js
  test/lsb.test.js
Labels: bug

#190 PR : Add `login restrictions` and `access token, refresh token` to `auth` files
  src/layers/controllers/auth.controller.js
  src/layers/passport/localStrategy.js
  src/layers/routes/middlewares/authMiddle.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
Labels: enhancement

#191 PR : Change encryption method
  package-lock.json
  package.json
  src/layers/services/auth.service.js
Labels: bug

#192 Fix: Refatoring kakaoMap api
  src/app.js
  src/layers/controllers/kakaoMap.controller.js
  src/layers/repositories/kakaoMap.repository.js
  src/layers/routes/kakaoMap.router.js
  src/layers/services/kakaoMap.service.js
Labels: enhancement

#193 update server : 0922
  package-lock.json
  package.json
  src/app.js
  src/layers/controllers/auth.controller.js
  src/layers/controllers/kakaoMap.controller.js
  src/layers/passport/localStrategy.js
  src/layers/repositories/kakaoMap.repository.js
  src/layers/routes/kakaoMap.router.js
  src/layers/routes/middlewares/authMiddle.js
  src/layers/services/auth.service.js
  src/layers/services/kakaoMap.service.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/models/auth.js
Labels: enhancement

#194 PR : Add try catch to repositories / Change the encryption method
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/services/auth.service.js
Labels: bug

#199 PR : Fix pagination type error
  src/layers/controllers/post.controller.js
Labels: bug

#200 PR : Fix pagination type error
  README.md
  src/layers/controllers/post.controller.js
Labels: bug

#201 PR : Fix: Add require to repositories
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/repositories/user.repository.js
  src/layers/services/auth.service.js
  src/sequelize/migrations/20220909081227-create-hot-post.js
  src/sequelize/migrations/20220924053833-create-hashauthnum.js
  src/sequelize/models/hashauthnum.js
Labels: bug

#202 PR : Fix: Add require to repositories
  README.md
  src/layers/controllers/auth.controller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/comment.repository.js
  src/layers/repositories/like.repository.js
  src/layers/repositories/notice.repository.js
  src/layers/repositories/recomment.repository.js
  src/layers/repositories/user.repository.js
  src/layers/services/auth.service.js
  src/sequelize/migrations/20220909081227-create-hot-post.js
  src/sequelize/migrations/20220924053833-create-hashauthnum.js
  src/sequelize/models/hashauthnum.js
Labels: bug

#204 Fix: Correct the wrong push
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
Labels: bug

#205 PR : `Fix: Correct the wrong push`
  src/layers/repositories/auth.repository.js
  src/layers/services/auth.service.js
Labels: bug

#206 PR : fix logic when img doesn't exist in UpdateUser API
  src/layers/controllers/user.controller.js
  src/layers/services/user.service.js
Labels: bug

#207 PR : fix logic when img doesn't exist in UpdateUser API
  src/layers/controllers/user.controller.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
Labels: bug

#209 PR : add deleteAuthnum scheduller to scheduller.js
  src/layers/controllers/user.controller.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/routes/auth.router.js
  src/layers/services/auth.service.js
  src/layers/services/user.service.js
Labels: bug, enhancement

#211 Refactore: update kakaoMap imgUrl
  README.md
  src/layers/controllers/auth.controller.js
  src/layers/controllers/user.controller.js
  src/layers/exceptModels/form/moodPoint.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/auth.repository.js
  src/layers/repositories/kakaoMap.repository.js
  src/layers/routes/auth.router.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/auth.service.js
  src/layers/services/kakaoMap.service.js
  src/layers/services/user.service.js
  src/sequelize/migrations/20220830044707-create-auth.js
  src/sequelize/migrations/20220924053833-create-hashauthnum.js
  src/sequelize/models/auth.js
  src/sequelize/models/hashauthnum.js
Labels: bug

#212 PR : signup and updatePw err message
  src/layers/services/auth.service.js
Labels: bug

#213 PR : signup and updatePw err message
  src/layers/services/auth.service.js
Labels: bug

#214 Hotfix: Change total point calc , postImageMiddle , postService w280 …
  src/app.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/post.service.js
Labels: bug

#215 Hotfix: Change total point calc , postImageMiddle , postService w280 …
  src/app.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/post.service.js
Labels: bug

#216 PR : add updateUserProfile default img to updateUser
  src/layers/controllers/user.controller.js
Labels: enhancement

#217 PR : add updateUserProfile default img to updateUser
  src/layers/controllers/user.controller.js
Labels: enhancement

#218 PR : likeStatus error in get post details
  src/layers/repositories/post.repository.js
  src/layers/services/post.service.js
Labels: bug

#219 PR : likeStatus error in get post details
  src/layers/repositories/post.repository.js
  src/layers/services/post.service.js
Labels: bug

#220 Refator: Fix imageUrl errors
  src/layers/repositories/auth.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/comment.service.js
  src/layers/services/kakaoMap.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
Labels: bug

#221 Refator: Fix imageUrl errors
  src/layers/repositories/auth.repository.js
  src/layers/routes/middlewares/postImageUploadMiddleware.js
  src/layers/services/comment.service.js
  src/layers/services/kakaoMap.service.js
  src/layers/services/post.service.js
  src/layers/services/user.service.js
Labels: bug

#222 PR : add error handling about profile default img delete problem
  src/layers/routes/middlewares/postImageUploadMiddleware.js
Labels: bug

#223 PR : add error handling about profile default img delete problem
  src/layers/routes/middlewares/postImageUploadMiddleware.js
Labels: bug

#225 Feature: update if not exist refPost send default image
  src/layers/controllers/notice.controller.js
  src/layers/controllers/post.controller.js
  src/layers/exceptModels/form/scheduller.js
  src/layers/repositories/post.repository.js
  src/layers/services/notice.service.js
  src/layers/services/post.service.js
Labels: bug

#226 Fix: fix kakaoMap imgUrl
  src/layers/services/kakaoMap.service.js
Labels: bug

#227 Fix: fix kakaoMap imgUrl
  src/layers/services/kakaoMap.service.js
Labels: bug
